# Generated by Django 5.2.7 on 2025-10-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adocao', '0002_animal_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='imagem',
            field=models.ImageField(upload_to='imgAnimal/'),
        ),
    ]
