# Generated by Django 5.2.6 on 2025-10-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adocao', '0004_perfilutilizador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilutilizador',
            name='confirmarPalavraPasse',
        ),
        migrations.RemoveField(
            model_name='perfilutilizador',
            name='usename',
        ),
        migrations.AddField(
            model_name='perfilutilizador',
            name='username',
            field=models.CharField(default='aaaaaaaaaaa', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='descricao',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(choices=[('gato', 'Gato'), ('cao', 'Cão')], max_length=10),
        ),
        migrations.AlterField(
            model_name='perfilutilizador',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='perfilutilizador',
            name='palavraPasse',
            field=models.CharField(max_length=255),
        ),
    ]
