# Generated by Django 5.2.6 on 2025-10-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adocao', '0005_remove_perfilutilizador_confirmarpalavrapasse_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilUtilizador',
        ),
        migrations.AlterField(
            model_name='animal',
            name='descricao',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(choices=[('gato', 'Gato'), ('cao', 'Cão')]),
        ),
    ]
