# Generated by Django 5.2.6 on 2025-10-27 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adocao', '0007_animal_padrinho_alter_animal_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='padrinho',
        ),
    ]
